# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _Scheduling(_Saas):
    _type = "scheduling"
    _icon_dir = "resources/saas/scheduling"


class Sidekiq(_Scheduling):
    _icon = "sidekiq.png"


# Aliases
